# NumPy

## O que é o NumPy?

O NumPy é uma poderosa biblioteca Python usada principalmente para realizar cálculos em Arrays Multidimensionais. O NumPy fornece um grande conjunto de funções e operações de biblioteca que ajudam os programadores a executar facilmente cálculos numéricos. Esses tipos de cálculos numéricos são amplamente utilizados em tarefas como:

* `Tarefas matemáticas`: NumPy é bastante útil para executar várias tarefas matemáticas como integração numérica, diferenciação, interpolação, extrapolação e muitas outras. O NumPy possui também funções incorporadas para álgebra linear e geração de números aleatórios. É uma biblioteca que pode ser usada em conjuto do <a href='https://github.com/scipy/scipy'>SciPy</a> e Matplotlib, substituindo o MATLAB quando se trata de tarefas matemáticas.

* `Processamento de Imagem e Computação Gráfica`: Imagens no computador são representadas como Arrays Multidimensionais de números. NumPy torna-se a escolha mais natural para o mesmo. O NumPy, na verdade, fornece algumas excelentes funções de biblioteca para rápida manipulação de imagens. Alguns exemplos são o espelhamento de uma imagem, a rotação de uma imagem por um determinado ângulo etc.

* `Modelos de Machine Learning`: Ao escrever algoritmos de Machine Learning, supõe-se que se realize vários cálculos numéricos em Array. Por exemplo, multiplicação de Arrays, transposição, adição, etc. O NumPy fornece uma excelente biblioteca para cálculos fáceis (em termos de escrita de código) e rápidos (em termos de velocidade). Os Arrays NumPy são usados para armazenar os dados de treinamento, bem como os parâmetros dos modelos de Machine Learning.


## Instalando

Existem diversas formas de instalar o numpy. A mais simples é instalar o pacote Anaconda (https://www.anaconda.com/distribution/) que já vem com o Python e diversas bibliotecas científicas e ciência de dados instaladas.

Outra forma, caso você já tenha o python instalado mas não o numpy, é o utilizar o gerenciador e pacotes pip, através do comando no seu **terminal**:

`$ pip install numpy`

ou dentro do jupyter

`!pip install numpy`

## Explorando a API do NumPy
### Importando numpy com o alias np

`np` é uma abreviação amplamente utilizada na comunidade python para o numpy.

In [1]:
!pip install numpy

You should consider upgrading via the 'c:\users\sgtty\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np

### 1D arrays

Array unidimensional, também chamado de vetor ou até mesmo matriz de 1 dimensão:


In [ ]:
a = np.array([1, 2, 3])
print(a)

Checando o tipo da variável a:

In [ ]:
type(a)

o nd significa n-dimensional


### Checando o tipo de dados do array

Diversos tipos de dados são possíveis em um array numpy, os mais comuns são os numéricos:

    int32
    int64
    float32
    float64


In [ ]:
a.dtype

### Substituindo elementos
Se trocarmos um elemento na posição 0 para o valor 10, dará certo:

In [ ]:
a[0] = 10
print(a)

Mas, se trocarmos para ponto flutuante, o numpy irá truncar a parte decimal, dado que o array que criamos é inteiro.

In [ ]:
a[0] = 1.2
print(a)

E se quisermos um dos elementos sendo um texto como fazíamos com as listas?

In [ ]:
lista = [1, 2, 'LC', 4]
array = np.array([1, 2, 'LC', 4])

print("Essa é a lista: ", lista)
print("Esse é o array: ", array)

O array converte todos os elementos para string. O numpy não aceita dados com tipos diferentes. Ter um tipo único, permite o numpy ser muito mais rápido.

### Porque usar numpy e não listas?
#### Numpy x Lists

    Tamanho - Numpy necessita de menos espaço
    Performance - escrito para ter alta performance
    Funcionalidade - SciPy e NumPy possuem operações de algebra linear built in.

<a href="https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference" target="_blank">Referência</a> 

#### Tempo de processamento

In [ ]:
"""
Código comparando performance entre numpy e listas em uma soma de arrays
"""

import time
import numpy as np

size_of_vec = 1000

def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1


t1 = pure_python_version()
t2 = numpy_version()
print(t1, t2)
print("Numpy is in this example " + str(t1/t2) + " faster!")

#### Diferença visual

In [ ]:
lista = [1, 2, 3, 4]
array = np.array([1, 2, 3, 4])

print("Essa é a lista: ", lista)
print("Esse é o array: ", array)

Repare que no array não temos a separação por vírgulas.
<br>



### 2D arrays

Matrizes podem ser consideradas um array de 2 dimensões.
_________________________________________________________________________________

Observação:

O NumPy possui também uma estrutura, matriz, mas não é recomendado utilizá-la pela própria documentação oficial e poderá ser removida no futuro.
_________________________________________________________________________________

Para criar uma matriz, basta aninhar múltiplas listas dentro de uma lista, como o exemplo a seguir:


In [ ]:
b = np.array([[9.0, 8.0, 7.0],
              [6.0, 5.0, 4.0]])
print(b)

### Exemplo 3D


<img src="tensor_3-2-5.png"  style="width: 500px" />

In [ ]:
c = np.array([[[0,   1,  2,  3,  4], [ 5,  6,  7,  8,  9]], 
              [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]],
              [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]]])
c

### Propriedades
#### Dimensão e formato

Dois conceitos importantes já mencionados acima é o de dimensão, formato e tamanho.

Para descobrir essas informações, basta acessar os atributos `ndim`, `shape` e `size`

In [ ]:
print(a.ndim)
print(a.shape)
print(a.size)

In [ ]:
print(b.ndim)
print(b.shape)
print(b.size)

In [ ]:
print(c.ndim)
print(c.shape)
print(c.size)

### Acessando e modificando elementos (Indexing & Slicing)

Dada a matriz a abaixo:

In [ ]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], 
              [8, 9, 10, 11, 12, 13, 14],
            [15, 16, 17, 18, 19, 20, 21]])
print(a)


Podemos acessar um elemento específico de forma similar a lista, utilzando a sintaxe de colchetes, com a diferença de que podemos separar cada posição com vírgulas: <br> <br>
$ array[IndiceLinha, IndiceColuna] $

Para uma array 2D, temos então a sintaxe:

Exemplo:


In [ ]:
a[1, 4]

Podemos também fazer dessa forma (menos comum):

In [ ]:
a[1][4]

Usar números negativos funciona de trás pra frente a indexação:


In [ ]:
a[1, -3]

Para pegar uma linha específica, podemos utilizar a sintaxe  `:` que pode ser lida como "todos" daquela dimensão (colunas).

Podemos ler então como: linha um, todas as colunas


In [ ]:
a[1:2]

In [ ]:
a[1:2, :]

Também podemos fazer assim simplesmente:


In [ ]:
a[1]

Porém, para coluna específica não tem jeito, precisamos usar `:`.

Leia-se: todas as linhas, coluna 2


In [ ]:
a[:, 2]

O operador `:` também conhecido como slicing, aceita o parâmetro:

    start
    end
    step

No formato

$ [ startindex : endindex : stepsize ] $ 

O stepsize basicamente é quantos elementos deve ser pular. Podemos pegar do elemento 1 ao 6 pulando de 2 em 2 por exemplo da linha 0.


In [ ]:
a[0, 1:6:2]

Funciona com negativo também:


In [ ]:
# negativo na coluna
a[0, 1:-1:2]

In [ ]:
# negativo no step
a[0, -1:1:-2]

Para mudar um elemento específico, basta usar o operador `=`

In [ ]:
a[1,5] = 20
a

Mudando uma coluna inteira para ser 5:


In [ ]:
a[:, 2] = 555
print(a)

Isso mostra uma característica fundamental do array do NumPy:

Ao alterar o pedaço da matriz recortada, você altera a matriz original enquanto slicing em listas geram cópias!

### Cópias do array

Um dos detalhes do numpy que pode facilmente levar à problemas é que se você faz um slide do array você não obtém um vetor totalmente novo. Ele é uma "view" do array original o que significa que eles compartilham dos mesmos dados.

Esse é o mesmo conceito de que as variáveis são apenas ponteiros e que variáveis distintas podem apontar para o mesmo objeto. This is similar to the idea that variables are just pointers, and that different variables may point to the same object (<a href="https://www.practicaldatascience.org/html/exercises/%5B../python_v_r.ipynb%5D">Python v. R / Variables as Pointers tutorial</a>). No caso de slices as duas variáveis acessam o mesmo dado mas apresentam ele de form distinta. Por exemplo:


In [3]:
my_array = np.array([1, 2, 3, 4])
my_array

array([1, 2, 3, 4])

In [4]:
my_slice = my_array[1:3]
my_slice

array([2, 3])

Uma vez que tanto my_array quanto my_slice apontam para o mesmo dado, mudanças que fizermos em um será propagada para o outro. Se modificarmos a entrada 2 no my_slice, essa mudança irá aparecer no my_array:

In [5]:
my_slice[0] = -1
my_slice


array([-1,  3])

In [6]:
my_array

array([ 1, -1,  3,  4])

Apesar de o my_array e o my_slice estarem acessando o mesmo dado eles estão indexados diferentes. Nós mudamos o índice 0 no my_slice e a mudança no my_array foi no índice 1. <br>
O mesmo não acontece com as listas

In [7]:
x = [1, 2, 3]
y = x[0:2]
y[0] = "a change"
y

['a change', 2]

In [8]:
x

[1, 2, 3]

Caso você não queira uma view você pode fazer o slice utilizando uma lista:

In [14]:
my_array = np.array([1, 2, 3, 4])
my_slice = my_array[1:3]
my_slice[0] = -1
my_array

array([ 1, -1,  3,  4])

In [18]:
my_array = np.array([1, 2, 3])
my_slice = my_array[[1,2]]
my_slice[0] = -1
my_array

array([1, 2, 3])

Ou utilizar uma cópia

In [10]:
my_array = np.array([1, 2, 3])
my_slice = my_array[[1,2]].copy()
my_slice[0] = -1
my_array

array([1, 2, 3])

### Inicializando arrays usando métodos internos

O NumPy já possui diversos métodos built-in para gerar arrays dos mais diversos tipos
array apenas com zeros

In [ ]:
np.zeros(5)

É possível gerar um array de qualquer formato, basta apenasr passar o formato como uma sequência (lista, tupla geralmente) como argumento


In [ ]:
np.zeros((2,3))

In [ ]:
np.zeros((2, 2, 3))

array apenas com 1

In [ ]:
np.ones((4, 2, 2), dtype='int32')

Um coisa muito comum é usar o np.ones para criar uma matriz de qualquer número fazendo a operação, exemplo:

In [ ]:
np.ones((2, 2)) * 10

Mas o numpy já tem uma opção mais elegante, o full:


In [ ]:
np.full((2, 2), 99)

Qualquer outro número copiando o formato de uma matriz existente


In [ ]:
np.full_like(c, 4)

### Números aleatórios
#### Números decimais aleatórios

O numpy tem um sub-módulo chamado random, que pode ser acessando via `np.random`. Embora o Python possua uma biblioteca padrão também chamada `random`, a biblioteca do *NumPy tem mais funcionalidades e gera diretamente vetores aleatórios*.

Cria um vetor segundo uma distribuição uniforme no intervalo [0,1):


In [ ]:
np.random.rand(4, 2)

Cria um vetor em que cada elemento segue uma distribuição normal com $\mu=10.0$ e $\sigma=1.0$

In [ ]:
v = np.random.normal(10, 1, (4,4))
print(v)


#### Números aleatórios inteiros:


Os argumentos principais são low, high e size, exemplo: criando uma matriz de 0 a 99 de 100 elementos:


In [ ]:
np.random.randint(low=0, high=100, size=100)


Para incluir o 100, basta trocar o high por 101

In [ ]:
np.random.randint(7, size=(3, 3))

Note que toda vez que rodarmos o código, os tensores terão valores diferentes. Podemos evitar esse comportamento, de forma que toda vez que o código é executado o tensor aleatório tenha o mesmo valor por meio da função seed, cujo argumento é a semente para o gerador de números aleatórios do Python:

In [ ]:
np.random.seed(1000)
v = np.random.rand(4)
print(v)

np.random.seed(1000)
v = np.random.rand(4)
print(v)


### Criar ranges

#### arange

Método que retorna elementos igualmente espaçados num step (por padrão, 1) dentro de um certo intervalo.


In [ ]:
np.arange(0, 10)

Step diferente de 1:


In [ ]:
np.arange(0, 5, 0.1)

#### linspace

Parecido com o arange, mas você diz quantos pontos você quer e o intervalo e ele define o espaçamento linear


In [ ]:
np.linspace(0, 100, num=10, retstep=True)


#### logspace

In [ ]:
np.logspace(0, 100, num=10, base=2.0)

### Matemática


#### Operação com escalares

In [ ]:
a = np.array([1, 2, 3, 4])
a

##### Soma

In [ ]:
a+2

##### Subtração:


In [ ]:
a - 2

##### Multiplicação

In [ ]:
a*2

##### Divisão

In [ ]:
a/2

##### Incrementar

In [ ]:
a += 2
a

##### Potência

In [ ]:
a**2

#### Operação entre arrays

Tudo que você consegue fazer com escalar, você consegue fazer com arrays elemento-a-elemento desde que os arrays tenham exatamente o mesmo tamanho, por exemplo, para soma:


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 1, 0])

# Exemplo de soma
a + b

In [ ]:
# Exemplo de multiplicação
a*b

In [ ]:
# Exemplo de potenciação
a**b

### Funções matemáticas
O NumPy oferece diversas funções matemáticas clássicas, como exponencial, logaritmo, seno, cosseno etc. Essas funções são aplicadas a todos os elementos do array
##### Função seno:

In [ ]:
np.sin(a)

##### Função cosseno

In [ ]:
np.cos(a)

#### Exponencial

In [ ]:
np.exp(a)

#### Log

In [ ]:
np.log(a)

### Estatística

O numpy vem com várias funções básicas de estatística como mínimo, máximo, média, mediana, etc.
Todos esses métodos aceitam o argumento `axis`. Para `axis=0` a conta é feita considerando-se as **linhas**. Para `axis=1` a conta é feita considerando-se as **colunas**.

In [ ]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

In [ ]:
np.min(stats)

In [ ]:
stats.max()

In [ ]:
#local do maior valor
stats.argmax()

In [ ]:
#local do menor valor
stats.argmin()

Mínimo por linha:


In [ ]:
np.min(stats, axis=1) 

Máximo por coluna:

In [ ]:
stats.max(axis=0)

Soma por coluna:

In [ ]:
np.sum(stats, axis=0)

In [ ]:
stats.sum(axis=0)

Média:


In [ ]:
np.mean(stats)

Desvio padrão

In [ ]:
stats.std()

### Reorganizar Array

Muitas vezes você quer mudar o formato de array, por exemplo, de 4 elementos pra uma matriz 2x2, ou situações similares.

Para isso, você pode utilizar a função `reshape`.


In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)
before

In [ ]:
after = before.reshape((4, 2)) # tem que possuir a mesma quantidade no size!
after

In [ ]:
before.reshape((-1, 2)) # o -1 representa quantas linhas for preciso para ter 2 colunas

In [ ]:
before.reshape(2, 2, 2)

### Apendar os vetores
#### Verticalmente

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2])

#### Horizontalmente

De forma similar ao anterior:


In [ ]:
# para arrays 1D
np.hstack((v1,v2))

#### para arrays 2D

In [ ]:
h1 = np.ones((2, 4))
print(h1)
print()

h2 = np.zeros((2, 2))
print(h2)

In [ ]:
np.hstack((h1, h2))

### Máscara Booleana e Seleção Avançada

Conceito super importante no numpy e no pandas é o de máscara booleana.

Ao utilizar qualquer operador booleano

    >
    <
    <=
    >=
    ==
    in

o numpy retorna um array de True e False no qual ele aplicou elemento a elemento aquele operador.

Suponha a matriz abaixo:


In [ ]:
mat = np.array([1, 10, 20, 30]).reshape(2, 2)
mat

Eu quero saber todos os elementos maiores que 10, eu posso aplicar:


In [ ]:
mat > 10

Me é retornado uma matriz de formato (2, 2) com True na posição dos elementos que são maiores que 10.

Os tensores booleanos podem ser usados para filtrar valores em um tensor, por exemplo:


In [ ]:
mat[mat > 10]

E será retornado um array com os elementos 20 e 30 como esperado.

Podemos fazer operações linha a linha ou coluna a coluna através de métodos auxiliares como any ou all:

    any: se qualquer elemento da linha for True, retorna True
    all: todos os elementos tem que ser True para retornar True

Exemplos:

Por coluna:


In [ ]:
mat

In [ ]:
np.any(mat > 10, axis=0)

Por linha:

In [ ]:
np.any(mat > 10, axis=1)

Geral:

In [ ]:
np.any(mat > 10)

Comparando arrays

In [ ]:
u = np.arange(4).reshape(2,2)
v = 2*np.ones((2,2))

In [ ]:
u

In [ ]:
v

In [ ]:
w = u > v
print(w)

In [ ]:
u[u > v]

### Operador AND

Similar ao `and` do python, podemos usar múltiplas condições para filtrar dados da nossa matriz com o operador `&`.


In [ ]:
mat

In [ ]:
filt = (mat > 10) & (mat <= 20)
mat[filt]

Observação: note que os colchetes além de melhorarem a legibilidade, são necessárias devido a ordem de precedência dos operadores python. Se não colocarmos os colchetes, dará um erro.


### Operador OR

Similar ao `or`, só que devemos utilizar `|`:


In [ ]:
filt = (mat == 1) | (mat >= 20)
mat[filt]

### Operador NOT

Similar ao `not`, mas devemos utilizar um til `~`.


In [ ]:
filt = (mat == 1) | (mat >= 20)
mat[~filt]

### Atribuir valores em determinadas condições
E podemos também atribuir um valor específico aos elementos de um vetor que satisfazem uma certa condições, por exemplo zerar todos os valores negativos:


In [ ]:
u = np.array([-1,  2, -3])
print("u =", u)
print()

u[u < 0] = 0
print("u =", u)

Usando **np.where(se condição, recebe valor, se não)**

In [ ]:
u = np.array([-1,  2, -3])
np.where(u<0, 0, u)

#### Seleção passando listas

Podemos selecionar elementos específicos de um array passando uma lista de posições:


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 5, 8]]

#### Nans

In [ ]:
a = np.array([[1, 2, 3, 4, 5], [np.nan, 7, 8, 9,10]])

In [ ]:
np.isnan(a)

In [ ]:
np.isnan(a).sum()

### Funcionalidades extras
#### Carregar dados de um arquivo

Vamos supor que temos um arquivo data.txt com o seguinte conteúdo:

1,13,21,11,196,75,4,3,34,6,7,8,0,1,2,3,4,5 <br>
3,42,12,33,766,75,4,55,6,4,3,4,5,6,7,0,11,12 <br>
1,22,33,11,999,11,2,1,78,0,1,2,9,8,7,1,76,88 <br>

Podemos gerar uma matriz a partir desse arquivo da seguinte forma:


In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

O primeiro argumento é o nome do arquivo.

No segundo argumento, delimiter, você especifica o que separa cada número individualmente no arquivo. Nesse caso é a vírgula, mas podería ser ;, espaços, ou tabs.

Podemos notar também que o numpy converteu para float nossos números, apesar de todos serem inteiros. Ele faz isso como uma medida preventiva dado que ele não sabe ao ler o arquivo qual tipo de dado que é.

Podemos importar os dados com um formato especificado usando o argumento `dtype='int'` ou podemos converter manualmente para inteiro usando a função astype:

In [ ]:
filedata.astype('int32')

Também podemos avisar o numpy quais são nossas colunas de interesse com o argumento `usecols`

In [ ]:
np.genfromtxt('data.txt', delimiter=',', usecols=[0,1,2,3], dtype='int')

Podemos também salvar uma matriz de uma forma mais otimizada não textual (binária) para uso futuro.

Isso gera um arquivo binário que inclusive salva o tipo de dado, nesse caso, int32.

Quando lido, vai converter corretamente o tipo daquele dado.



In [ ]:
np.save('data_saved', filedata.astype('int32'))


Para ler os dados que acabamos de salvar, basta usar o `np.load`:


In [ ]:
np.load('data_saved.npy')

### Álgebra Linear

Da definição do Wikipédia:

    Álgebra linear é um ramo da matemática que surgiu do estudo detalhado de sistemas de equações lineares, sejam elas algébricas ou diferenciais. A álgebra linear utiliza alguns conceitos e estruturas fundamentais da matemática como vetores, espaços vetoriais, transformações lineares, sistemas de equações lineares e matrizes.

O numpy nos permite executar diversas diversas operações de álgebra linear, mostradas a seguir:


In [ ]:
a = np.ones((2, 3))
print(a)
print()

b = np.full((3, 2), 2)
print(b)
print()

c = np.identity(5)
print(c)

##### Transposição

<img src="transposicao.png"  style="width: 400px" />

A operação de transposição pode ser feita da seguinte forma:

In [ ]:
np.transpose(a)

Ou acessando o atributo T:

In [ ]:
a.T

#### Multiplicação de matrizes

A tradicional multiplicação de matrizes, como mostra a imagem abaixo:

<img src="multiplicacao.gif"  style="width: 400px" />

pode ser feita no numpy simplesmente chamando `matmul`


In [ ]:
np.matmul(a, b)

Operador `@` executa a função anterior:


In [ ]:
a @ b

Se utilizarmos o símbolo * teremos a múltiplicação elemento à elemento e precisaremos de matrizes de mesmo tamanho

In [ ]:
a = np.array([[1, 2], [3, 2]])
b = np.array([[4, 5], [2, 1]])
print(a)
print()
print(b)
a * b

Outras funcções de Álgebra Linear: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

    Trace
    Decomposição de vetores
    Autovalor/autovetor
    Norma da Matriz
    Inversa
    Etc...


Referências   <br>
<a href="https://github.com/numpy/numpy" target="_blank">NumPy GitHub</a>  <br>
<a href="https://docs.scipy.org/doc/numpy/reference/" target="_blank">Documentação oficial</a>   <br>
<a href="https://docs.scipy.org/doc/numpy/reference/routines.math.html" target="_blank">Funções matemáticas</a>   <br>
<a href="https://docs.scipy.org/doc/numpy/reference/routines.linalg.html" target="_blank">Funções de Álgebra Linear</a>   <br>
<a href="http://www.opl.ufc.br/pt/post/numpy/" target="_blank">Outros</a> 
    

## Outros tópicos
* Broadcasting: operações com vetores de dimensões distintas

<a href="http://www.opl.ufc.br/pt/post/numpy/" target="_blank">Referência</a> 

## Exercícios

1 - Substitua os valores ímpares do seguinte array por 0:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>
Utilizando list compreension e duas maneiras distintas com o numpy

In [41]:
matriz = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

m1 = np.array([0 if n%2 != 0 else n for n in matriz])

m2 = matriz.copy()
m2[::2] = 0

m3 = matriz.copy()
print(np.where(m3%2==0, m3, 0))

[0 2 0 4 0 6 0 8 0]


2 - Concatene os vetores abaixo verticalmente e horizontalmente <br>
a = np.arange(10).reshape(2,-1) <br>
b = np.repeat(1, 10).reshape(2,-1)

In [49]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

vertical = np.vstack([a,b])
horizontal = np.hstack([a,b])
print(vertical)
print()
print(horizontal)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


3 - Importe as 4 primeiras colunas do dataset do íris com o numpy e print as 10 primeiras linhas <br> 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [55]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', usecols=[0,1,2,3]) #max_rows=10
iris[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

4 - Calcule a média, mediana e desvio padrão da coluna sepallenght

In [74]:
media = np.mean(iris[:,0])

mediana = np.median(iris[:,0])

dp = np.std(iris[:,0])

print(media, mediana, dp)

5.843333333333334 5.8 0.8253012917851409


5 - Crie um vetor normalizado da coluna sepallength cujos valores estejam entre 0 e 1

In [78]:
irisNormal = ((iris[:,0] - media) / dp)
filt = (irisNormal > 0) & (irisNormal < 1)
irisNormal[filt]

array([0.67450115, 0.79566902, 0.55333328, 0.91683689, 0.06866179,
       0.18982966, 0.31099753, 0.4321654 , 0.06866179, 0.31099753,
       0.55333328, 0.31099753, 0.67450115, 0.91683689, 0.18982966,
       0.18982966, 0.18982966, 0.55333328, 0.31099753, 0.4321654 ,
       0.55333328, 0.55333328, 0.79566902, 0.79566902, 0.67450115,
       0.67450115, 0.79566902, 0.18982966, 0.55333328, 0.4321654 ,
       0.31099753, 0.67450115, 0.67450115, 0.55333328, 0.31099753,
       0.55333328, 0.67450115, 0.18982966, 0.55333328, 0.79566902,
       0.4321654 , 0.06866179])

6 - Filtre a matriz para conter apenas dados nos quais petallength (3ª columna) > 1.5 e sepallength (1ª coluna) < 5.0

In [80]:
filtro = (iris[:,2] > 1.5) & (iris[:,0] < 5)
iris[filtro]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

7 - Esses dados possuem nans?

In [83]:
np.isnan(iris).sum()

0

8 - Crie uma coluna de volume sabendo que o volume representa (pi x petallength x sepal_length^2)/3

In [126]:
volume = ((np.pi * iris[:,2] * iris[:,0]**2)/3).reshape(150,1)
novoIris = np.hstack([iris, volume])
novoIris

array([[5.10000000e+00, 3.50000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.81326516e+01],
       [4.90000000e+00, 3.00000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.52004985e+01],
       [4.70000000e+00, 3.20000000e+00, 1.30000000e+00, 2.00000000e-01,
        3.00723721e+01],
       [4.60000000e+00, 3.10000000e+00, 1.50000000e+00, 2.00000000e-01,
        3.32380503e+01],
       [5.00000000e+00, 3.60000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.66519143e+01],
       [5.40000000e+00, 3.90000000e+00, 1.70000000e+00, 4.00000000e-01,
        5.19116770e+01],
       [4.60000000e+00, 3.40000000e+00, 1.40000000e+00, 3.00000000e-01,
        3.10221803e+01],
       [5.00000000e+00, 3.40000000e+00, 1.50000000e+00, 2.00000000e-01,
        3.92699082e+01],
       [4.40000000e+00, 2.90000000e+00, 1.40000000e+00, 2.00000000e-01,
        2.83832424e+01],
       [4.90000000e+00, 3.10000000e+00, 1.50000000e+00, 1.00000000e-01,
        3.77148198e+01],
       [5.40000000e+00, 3.7000

## Mais coisas interessantes...


#### Tipo de dado e tamanho

Na sessão Checando o tipo de dados do array já foi dito dos tipos de dados, mas agora falaremos da diferença de tamanhos que isso ocupa na memória.

Então, temos as variáveis a e b criadas anteriormente com os seguintes tipos:


In [ ]:
a.dtype

In [ ]:
b.dtype


Por padrão, se o python instalado é 64 bits, ele irá criar tipos int ou float de 64 bits. Caso seu python fosse 32 bits, seria int32 e float32.

Vamos criar uma outra array, a16, com o tipo inteiro de 16 bits.


In [ ]:
a16 = np.array([1, 2, 3], dtype=np.int16)
a16


Note que por ser um tipo diferente do padrão, ele ressalta ao imprimir.

Para descobrir quanto cada elemento individualmente ocupa na memória, podemos acessar o atributo itemsize:


In [ ]:
a.itemsize


Ele retorna 8 e não 64! Isso é porque ele já converteu os bits para bytes. Bytes é o conjunto de 8 bits.

Logo:

$ 64/8=8 $

Já nosso array int16, temos:


In [ ]:
a16.itemsize

Uma vez que:

$ 16/8 = 2 $

In [ ]:
# quantidade de elementos total
a.size

Quantidade de elementos vezes o tamanho de cada elemento nos dará o tamanho total de bytes que o array inteiro ocupa:


In [ ]:
a.size * a.itemsize


Mas ao invés de calcular isso, podemos simplesmente acessar o atributo `nbytes`, que já é o tamanho total de bytes ocupado pelo array:


In [ ]:
a.nbytes

**Observação**

Geralmente não é necessário reduzir o número de bits a não ser que você tenha certeza que um tamanho reduzido vai atender sua necessidade e você quer ser extremamente eficiente.
